// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBraUFxLP_FniIM2iYIXdkpSlxSu0Hbofg',
    appId: '1:117145065516:web:cc1e04c6b546afedffd989',
    messagingSenderId: '117145065516',
    projectId: 'flutter-authen-7ad3e',
    authDomain: 'flutter-authen-7ad3e.firebaseapp.com',
    storageBucket: 'flutter-authen-7ad3e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyY4QVEUtX6K9AVNRtRswZitO8igLt47w',
    appId: '1:117145065516:android:a3db1a7a5c537cffffd989',
    messagingSenderId: '117145065516',
    projectId: 'flutter-authen-7ad3e',
    storageBucket: 'flutter-authen-7ad3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPk4xBUIwmU31kbpkwn-36yqjnyErvjEs',
    appId: '1:117145065516:ios:9d34d4d05785ef69ffd989',
    messagingSenderId: '117145065516',
    projectId: 'flutter-authen-7ad3e',
    storageBucket: 'flutter-authen-7ad3e.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPk4xBUIwmU31kbpkwn-36yqjnyErvjEs',
    appId: '1:117145065516:ios:9d34d4d05785ef69ffd989',
    messagingSenderId: '117145065516',
    projectId: 'flutter-authen-7ad3e',
    storageBucket: 'flutter-authen-7ad3e.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBraUFxLP_FniIM2iYIXdkpSlxSu0Hbofg',
    appId: '1:117145065516:web:ab403901d18d3427ffd989',
    messagingSenderId: '117145065516',
    projectId: 'flutter-authen-7ad3e',
    authDomain: 'flutter-authen-7ad3e.firebaseapp.com',
    storageBucket: 'flutter-authen-7ad3e.firebasestorage.app',
  );
}
